version: "3"

services:
  api:
    build: ./

    depends_on:
      - redis

    links:
      - redis

    volumes:
      - /app/node_modules
      - ./:/app

    command: sh -c "npm run build && pm2-runtime ./deployment/ecosystem.config.json"

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - NODE_ENV=production

    ports:
      - 3000:3000

  client:
    stdin_open: true

    depends_on:
      - api

    links:
      - api

    build: ../gloss-adder-frontend

    volumes:
      - /app/node_modules
      - ../gloss-adder-frontend:/app

    command: sh -c "rm -rf .next && npm run build && npm start"

    environment:
      - API_PORT=3000
      - NODE_ENV=production

    ports:
      - 3001:3001

  nginx:
    image: "nginx:stable"

    depends_on:
      - api
      - client

    links:
      - api
      - client

    restart: always

    ports:
      - "80:80"

    volumes:
      - "./deployment/nginx.conf:/etc/nginx/nginx.conf"

  redis:
    image: "redis:alpine"
