version: "3"

services:
  redis:
    image: "redis:latest"

  api:
    build: ./

    depends_on:
      - redis

    links:
      - redis

    volumes:
      - /app/node_modules
      - ./:/app

    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000

    ports:
      - 3000:3000

  client:
    stdin_open: true

    links:
      - api 

    build: ../gloss-adder-frontend

    volumes:
      - /app/node_modules
      - ../gloss-adder-frontend:/app

    command: sh -c "npm start"

    environment:
      - NEXT_PUBLIC_SERVER_URL=/api
      - NODE_ENV=production

    ports:
      - 3001:3001

  nginx:
    image: "nginx:stable"
    
    depends_on:
      - api
      - client

    links:
      - api
      - client
    
    restart: always 

    ports:
      - '80:80'

    volumes:
       - "./deployment/nginx.conf:/etc/nginx/nginx.conf"
